const questionBank = {
  medicine: [
    {
      q: "What was the primary cause of the Black Death in 14th century Europe?",
      options: ["Bubonic plague", "Smallpox", "Typhus", "Cholera"],
      answer: "Bubonic plague"
    },
    {
      q: "Who was known as the 'Father of Medicine'?",
      options: ["Hippocrates", "Galen", "Vesalius", "Harvey"],
      answer: "Hippocrates"
    },
    {
      q: "What was Galen’s theory about the cause of disease?",
      options: [
        "Imbalance of the four humours",
        "Demonic possession",
        "Miasma in the air",
        "Bacterial infection"
      ],
      answer: "Imbalance of the four humours"
    },
    {
      q: "What was the main method of treatment in medieval hospitals?",
      options: [
        "Prayer and care",
        "Surgery",
        "Herbal remedies",
        "Blood transfusion"
      ],
      answer: "Prayer and care"
    },
    {
      q: "Which invention in the Renaissance improved anatomical knowledge?",
      options: ["Printing press", "Microscope", "X-ray machine", "Stethoscope"],
      answer: "Printing press"
    },
    {
      q: "Who published 'De humani corporis fabrica' in 1543?",
      options: [
        "Andreas Vesalius",
        "William Harvey",
        "Ambroise Paré",
        "Galen"
      ],
      answer: "Andreas Vesalius"
    },
    {
      q: "Who discovered the circulation of blood?",
      options: [
        "William Harvey",
        "Andreas Vesalius",
        "Hippocrates",
        "Galen"
      ],
      answer: "William Harvey"
    },
    {
      q: "What was the main role of barber surgeons?",
      options: [
        "Performing minor surgeries and bloodletting",
        "Writing medical texts",
        "Diagnosing diseases",
        "Preparing herbal remedies"
      ],
      answer: "Performing minor surgeries and bloodletting"
    },
    {
      q: "What was the main belief about the cause of disease before germ theory?",
      options: [
        "Imbalance of humours",
        "Bacteria",
        "Viruses",
        "Genetics"
      ],
      answer: "Imbalance of humours"
    },
  { q: "Which theory suggested illness was caused by an imbalance of body fluids?", options: ["Four Humours", "Germ Theory", "Miasma", "Spontaneous Generation"], answer: "Four Humours" },
  { q: "Which Greek doctor’s ideas were adapted by Galen?", options: ["Hippocrates", "Vesalius", "Harvey", "Jenner"], answer: "Hippocrates" },
  { q: "What was the main explanation for the cause of the Black Death in 1348 according to Medieval belief?", options: ["Miasma", "Germs", "Bad diet", "Contaminated water"], answer: "Miasma" },
  { q: "What did most Medieval hospitals focus on providing?", options: ["Care for the sick", "Surgery", "Isolation wards", "Public health campaigns"], answer: "Care for the sick" },
  { q: "Which religious group ran many hospitals in Medieval England?", options: ["Monks and nuns", "Surgeons", "Physicians", "Barber-surgeons"], answer: "Monks and nuns" },
  { q: "Who proved that the heart pumps blood around the body in 1628?", options: ["William Harvey", "Andreas Vesalius", "Ambroise Paré", "John Hunter"], answer: "William Harvey" },
  { q: "What did Andreas Vesalius study to improve knowledge of anatomy?", options: ["Human dissection", "Animal dissection", "Microscopy", "Blood transfusion"], answer: "Human dissection" },
  { q: "What was the name given to bad air believed to cause disease?", options: ["Miasma", "Humours", "Sepsis", "Contagion"], answer: "Miasma" },
  { q: "Which book by Vesalius challenged Galen's anatomy?", options: ["The Fabric of the Human Body", "Observationes Medicae", "De Motu Cordis", "On Surgery"], answer: "The Fabric of the Human Body" },
  { q: "Ambroise Paré promoted the use of what instead of boiling oil for wounds?", options: ["Ointment", "Alcohol", "Saltwater", "Herbal paste"], answer: "Ointment" },
  { q: "What was a common Medieval treatment for balancing the humours?", options: ["Bloodletting", "Antibiotics", "Vaccination", "Antiseptic"], answer: "Bloodletting" },
  { q: "Which Renaissance figure studied circulation but faced slow acceptance?", options: ["William Harvey", "Louis Pasteur", "Edward Jenner", "Joseph Lister"], answer: "William Harvey" },
  { q: "During the Great Plague of 1665, which public health measure was used?", options: ["Quarantine", "Antibiotics", "X-rays", "Surgical masks"], answer: "Quarantine" },
  { q: "Who introduced the ligature to tie arteries instead of cauterisation?", options: ["Ambroise Paré", "Vesalius", "Harvey", "Hunter"], answer: "Ambroise Paré" },
  { q: "What was the main role of apothecaries in the Renaissance?", options: ["Prepare medicines", "Perform surgery", "Lead hospitals", "Conduct autopsies"], answer: "Prepare medicines" },
  { q: "What material did Harvey use to demonstrate circulation?", options: ["Valves in veins", "Microscope slides", "Animal hearts", "Wax models"], answer: "Valves in veins" },
  { q: "What did people believe aligned with humours to affect health?", options: ["Seasons", "Planets", "Mountains", "Oceans"], answer: "Seasons" },
  { q: "Who encouraged observation over reliance on ancient texts?", options: ["Vesalius", "Hippocrates", "Pasteur", "Fleming"], answer: "Vesalius" },
  { q: "What was a 'pest house' used for?", options: ["Isolating plague victims", "Training physicians", "Making medicine", "Keeping livestock"], answer: "Isolating plague victims" },
  { q: "What theory began to be questioned in the Renaissance due to new discoveries?", options: ["Four Humours", "Germ Theory", "Cell Theory", "Evolution"], answer: "Four Humours" },
  { q: "Who developed the smallpox vaccination in 1796?", options: ["Edward Jenner", "Louis Pasteur", "Robert Koch", "Joseph Lister"], answer: "Edward Jenner" },
  { q: "Which French scientist developed Germ Theory in 1861?", options: ["Louis Pasteur", "Robert Koch", "Joseph Lister", "Alexander Fleming"], answer: "Louis Pasteur" },
  { q: "Robert Koch identified the bacteria for which disease in 1882?", options: ["Tuberculosis", "Cholera", "Anthrax", "Plague"], answer: "Tuberculosis" },
  { q: "Who promoted the use of carbolic acid in surgery?", options: ["Joseph Lister", "John Snow", "William Harvey", "Florence Nightingale"], answer: "Joseph Lister" },
  { q: "Which anaesthetic was first used successfully in surgery in 1846?", options: ["Ether", "Chloroform", "Nitrous oxide", "Cocaine"], answer: "Ether" },
  { q: "Who developed chloroform as an anaesthetic for childbirth?", options: ["James Simpson", "Joseph Lister", "Robert Liston", "Louis Pasteur"], answer: "James Simpson" },
  { q: "What did John Snow link to contaminated water in 1854?", options: ["Cholera", "Typhus", "Smallpox", "Plague"], answer: "Cholera" },
  { q: "What did Florence Nightingale emphasise in hospital care?", options: ["Cleanliness", "Anaesthetics", "Antibiotics", "Surgery"], answer: "Cleanliness" },
  { q: "Which engineer helped design London’s sewer system after the Great Stink?", options: ["Joseph Bazalgette", "Isambard Kingdom Brunel", "Robert Stephenson", "Thomas Telford"], answer: "Joseph Bazalgette" },
  { q: "In what year was the Public Health Act making local councils responsible passed?", options: ["1875", "1848", "1858", "1901"], answer: "1875" },
  { q: "Which disease outbreak in 1831–32 caused major reform pressure?", options: ["Cholera", "Smallpox", "Influenza", "Plague"], answer: "Cholera" },
  { q: "What was Lister’s antiseptic method intended to reduce?", options: ["Infection rates", "Pain", "Bleeding", "Medical costs"], answer: "Infection rates" },
  { q: "Pasteur’s work led to development of vaccines for which disease in 1880?", options: ["Chicken cholera", "Polio", "HIV", "Influenza"], answer: "Chicken cholera" },
  { q: "Which group opposed smallpox vaccination in the 19th century?", options: ["Anti-Vaccination League", "Public Health Association", "Royal Society", "Medical Council"], answer: "Anti-Vaccination League" },
  { q: "What was a common problem with early anaesthetics?", options: ["Overdoses", "Addiction", "Ineffectiveness", "Allergy"], answer: "Overdoses" },
  { q: "Who discovered the bacteria causing anthrax in 1876?", options: ["Robert Koch", "Louis Pasteur", "Edward Jenner", "Joseph Lister"], answer: "Robert Koch" },
  { q: "What invention improved surgical lighting in the 19th century?", options: ["Electric bulbs", "Oil lamps", "Gas mantles", "Candle lanterns"], answer: "Electric bulbs" },
  { q: "Which war helped Nightingale promote hospital reform?", options: ["Crimean War", "Boer War", "WW1", "WW2"], answer: "Crimean War" },
  { q: "What did the 1848 Public Health Act establish?", options: ["Central Board of Health", "Compulsory vaccination", "State hospitals", "National Health Service"], answer: "Central Board of Health" },
  { q: "Which 19th-century law made vaccination compulsory?", options: ["1853 Vaccination Act", "1867 Health Act", "1875 Public Health Act", "1898 Vaccination Act"], answer: "1853 Vaccination Act" },
  { q: "What was the main medical problem caused by trench conditions in WW1?", options: ["Trench foot", "Scurvy", "Cholera", "Smallpox"], answer: "Trench foot" },
  { q: "Which device reduced deaths from leg fractures in WW1?", options: ["Thomas Splint", "Iron lung", "Portable X-ray", "Stretcher"], answer: "Thomas Splint" },
  { q: "What solution was used in WW1 to treat infected wounds?", options: ["Carrel-Dakin", "Phenol", "Alcohol", "Iodine"], answer: "Carrel-Dakin" },
  { q: "Who developed techniques for skin grafts in WW1?", options: ["Harold Gillies", "Joseph Lister", "Florence Nightingale", "Archibald McIndoe"], answer: "Harold Gillies" },
  { q: "What mobile technology helped locate shrapnel in WW1?", options: ["X-ray units", "MRI scanners", "CT scanners", "Ultrasound"], answer: "X-ray units" },
  { q: "Which organisation provided frontline ambulance services in WW1?", options: ["RAMC", "FANY", "Red Cross", "British Legion"], answer: "RAMC" },
  { q: "Which group of women provided first aid and transport in WW1?", options: ["FANY", "WAAF", "WRNS", "VAD"], answer: "FANY" },
  { q: "Which antibiotic was mass-produced in WW2?", options: ["Penicillin", "Streptomycin", "Erythromycin", "Tetracycline"], answer: "Penicillin" },
  { q: "What year was the NHS founded?", options: ["1948", "1945", "1950", "1939"], answer: "1948" },
  { q: "Who discovered penicillin in 1928?", options: ["Alexander Fleming", "Howard Florey", "Ernst Chain", "Joseph Lister"], answer: "Alexander Fleming" },
  { q: "Which scan uses magnets to produce images of the body?", options: ["MRI", "X-ray", "CT", "PET"], answer: "MRI" },
  { q: "Which illness saw a global pandemic in 1918–1919?", options: ["Spanish Flu", "Cholera", "Polio", "Typhus"], answer: "Spanish Flu" },
  { q: "Which disease has seen rising resistance to antibiotics?", options: ["MRSA", "Polio", "Tuberculosis", "Cholera"], answer: "MRSA" },
  { q: "What virus was first identified in 1983 as the cause of AIDS?", options: ["HIV", "Influenza", "Hepatitis C", "Ebola"], answer: "HIV" },
  { q: "Which vaccine was introduced in the UK in 1955?", options: ["Polio", "Measles", "Flu", "HPV"], answer: "Polio" },
  { q: "What is the main advantage of keyhole surgery?", options: ["Smaller incisions", "Lower cost", "No anaesthetic", "Faster imaging"], answer: "Smaller incisions" },
  { q: "Which scanning technology was introduced in the 1970s?", options: ["CT", "MRI", "PET", "Ultrasound"], answer: "CT" },
  { q: "What was the UK government’s main measure against COVID-19 in 2020?", options: ["Lockdowns", "Antibiotics", "Compulsory masks only", "Herd immunity policy"], answer: "Lockdowns" },
  { q: "Which disease was declared eradicated by the WHO in 1980?", options: ["Smallpox", "Polio", "Cholera", "Measles"], answer: "Smallpox" },
  { q: "Who developed the first heart transplant in 1967?", options: ["Christiaan Barnard", "Jonas Salk", "Howard Florey", "Robert Edwards"], answer: "Christiaan Barnard" },
  { q: "Who developed the polio vaccine in 1955?", options: ["Jonas Salk", "Alexander Fleming", "Edward Jenner", "Louis Pasteur"], answer: "Jonas Salk" },
  { q: "Which discovery did Paul Ehrlich make in 1909?", options: ["Salvarsan 606", "Penicillin", "Chloroform", "Insulin"], answer: "Salvarsan 606" },
  { q: "Who is known as the father of microbiology?", options: ["Louis Pasteur", "Robert Koch", "Joseph Lister", "William Harvey"], answer: "Louis Pasteur" },
  { q: "Which individual pioneered IVF treatment in the UK?", options: ["Robert Edwards", "Patrick Steptoe", "Christiaan Barnard", "John Snow"], answer: "Robert Edwards" },
  { q: "What was Howard Florey’s role in penicillin development?", options: ["Mass production", "Discovery", "Purification", "Public promotion"], answer: "Mass production" },
  { q: "Which law in 1942 promised post-war healthcare reforms in Britain?", options: ["Beveridge Report", "Public Health Act", "National Insurance Act", "Vaccination Act"], answer: "Beveridge Report" },
  { q: "Which war led to improved blood transfusion storage methods?", options: ["WW1", "WW2", "Korean War", "Crimean War"], answer: "WW1" },
  { q: "Who co-developed penicillin with Fleming?", options: ["Howard Florey and Ernst Chain", "Louis Pasteur and Robert Koch", "Jonas Salk and James Watson", "Christiaan Barnard and Harold Gillies"], answer: "Howard Florey and Ernst Chain" },
  { q: "Which public health measure was introduced in 1956 to reduce smoking-related illness?", options: ["Health warnings", "Tax increase", "Advertising ban", "Free check-ups"], answer: "Health warnings" },
  { q: "Which disease saw a major UK vaccination campaign in 1964?", options: ["Measles", "Smallpox", "TB", "Polio"], answer: "Measles" },
  { q: "Who first identified DNA’s double-helix structure in 1953?", options: ["Watson and Crick", "Fleming and Florey", "Pasteur and Koch", "Salk and Barnard"], answer: "Watson and Crick" },
  { q: "Which government act in 2006 banned smoking in public places in England?", options: ["Health Act", "Clean Air Act", "Public Health Act", "Tobacco Control Act"], answer: "Health Act" },
  { q: "Which discovery allowed organ transplants to become more successful?", options: ["Immunosuppressant drugs", "CT scans", "Antiseptics", "Keyhole surgery"], answer: "Immunosuppressant drugs" },
  { q: "Who discovered insulin in 1921?", options: ["Banting and Best", "Pasteur and Koch", "Florey and Chain", "Harvey and Vesalius"], answer: "Banting and Best" },
  { q: "Which act in 1875 improved public health through sanitation?", options: ["Public Health Act", "Vaccination Act", "Health and Safety Act", "Sanitation Act"], answer: "Public Health Act" },
  { q: "Which disease was the focus of the first mass NHS vaccination programme?", options: ["Diphtheria", "Measles", "Polio", "TB"], answer: "Diphtheria" },
  { q: "What medical advance did Charles Booth’s surveys help promote?", options: ["Public health reform", "Penicillin", "MRI scans", "Keyhole surgery"], answer: "Public health reform" },
  { q: "Which campaign in the 1980s used 'Don’t Die of Ignorance'?", options: ["HIV/AIDS awareness", "Anti-smoking", "Heart disease prevention", "Flu vaccination"], answer: "HIV/AIDS awareness" },
  { q: "Who developed the first successful chemotherapy drug?", options: ["Paul Ehrlich", "Howard Florey", "Louis Pasteur", "Alexander Fleming"], answer: "Paul Ehrlich" },
  { q: "Which act in 1956 targeted air pollution?", options: ["Clean Air Act", "Public Health Act", "Environmental Act", "Health Act"], answer: "Clean Air Act" }
  ],
  elizabethan: [
    {
      q: "Who was the Earl of Leicester?",
      options: [
        "Robert Dudley, a close favourite of Elizabeth",
        "Francis Drake",
        "William Cecil",
        "Walter Raleigh"
      ],
      answer: "Robert Dudley, a close favourite of Elizabeth"
    },
    {
      q: "Who ascended to the English throne in 1558?",
      options: ["Mary I", "Elizabeth I", "James I", "Henry VIII"],
      answer: "Elizabeth I"
    },
    {
      q: "What was the main religion established by Elizabeth I's Religious Settlement?",
      options: ["Catholicism", "Anglicanism", "Puritanism", "Lutheranism"],
      answer: "Anglicanism"
    },
    {
      q: "Which law made Elizabeth the Supreme Governor of the Church of England?",
      options: ["Act of Uniformity", "Act of Supremacy", "Elizabethan Religious Settlement", "Penal Laws"],
      answer: "Act of Supremacy"
    },
    {
      q: "Which Spanish event in 1588 was a key moment in Elizabethan England?",
      options: ["Defeat of the Spanish Armada", "Battle of Lepanto", "Spanish Inquisition", "Treaty of Tordesillas"],
      answer: "Defeat of the Spanish Armada"
    },
    {
      q: "What was the name of Elizabeth I's principal secretary and advisor?",
      options: ["William Cecil", "Francis Walsingham", "Robert Dudley", "Walter Raleigh"],
      answer: "William Cecil"
    },
    {
      q: "What was the significance of the 1559 Act of Uniformity?",
      options: ["It established the Book of Common Prayer", "It banned Catholic Mass", "It dissolved monasteries", "It outlawed Puritanism"],
      answer: "It established the Book of Common Prayer"
    },
    {
      q: "Who was the English sea captain famous for raiding Spanish ships during Elizabeth's reign?",
      options: ["Francis Drake", "John Hawkins", "Walter Raleigh", "Martin Frobisher"],
      answer: "Francis Drake"
    },
    {
      q: "Which Elizabethan theatre was associated with William Shakespeare?",
      options: ["The Globe Theatre", "The Swan Theatre", "The Rose Theatre", "The Curtain Theatre"],
      answer: "The Globe Theatre"
    },
    {
      q: "Which rebellion in 1569 challenged Elizabeth’s authority in the north of England?",
      options: ["Northern Rebellion", "Pilgrimage of Grace", "Essex Rebellion", "Wyatt’s Rebellion"],
      answer: "Northern Rebellion"
    },
    {
      q: "What was the purpose of the Elizabethan Poor Laws?",
      options: ["To provide relief for the poor", "To punish vagrants severely", "To enforce religious uniformity", "To regulate wages"],
      answer: "To provide relief for the poor"
    },
  { q: "In which year did Elizabeth I become queen?", options: ["1558", "1559", "1560", "1561"], answer: "1558" },
  { q: "What was Elizabeth's main religious compromise in 1559?", options: ["Religious Settlement", "Papal recognition", "Puritan reforms", "Lutheran adoption"], answer: "Religious Settlement" },
  { q: "Which body advised Elizabeth on state matters?", options: ["Privy Council", "Parliament", "House of Lords", "Court of Star Chamber"], answer: "Privy Council" },
  { q: "Who was Elizabeth’s Chancellor of the Exchequer?", options: ["William Cecil", "Robert Dudley", "Francis Walsingham", "Mary Tudor"], answer: "William Cecil" },
  { q: "Which law made attendance at Church of England services compulsory?", options: ["Act of Uniformity", "Act of Supremacy", "Poor Law", "Statute of Praemunire"], answer: "Act of Uniformity" },
  { q: "The Act of Supremacy in 1559 did what?", options: ["Made Elizabeth head of the church", "Reinstated the Pope", "Ended Protestantism", "Banned Puritans"], answer: "Made Elizabeth head of the church" },
  { q: "What was the title given to those who did not accept the Religious Settlement?", options: ["Puritans", "Catholics", "Calvinists", "Anglicans"], answer: "Puritans" },
  { q: "Which group continued loyalty to Catholicism in England?", options: ["Recusants", "Anglicans", "Puritans", "Huguenots"], answer: "Recusants" },
  { q: "In which year was the Religious Settlement passed?", options: ["1559", "1560", "1563", "1569"], answer: "1559" },
  { q: "What was Parliament's main role under Elizabeth?", options: ["Pass laws and approve taxes", "Appoint the monarch", "Lead the church", "Run local government"], answer: "Pass laws and approve taxes" },
  { q: "Elizabeth’s legitimacy was challenged due to her birth by?", options: ["Henry VIII’s later marriage to Anne Boleyn", "Papal authority", "Scottish claim", "French invasion"], answer: "Henry VIII’s later marriage to Anne Boleyn" },
  { q: "Who was the most trusted spy master under Elizabeth?", options: ["Francis Walsingham", "William Cecil", "Robert Dudley", "Mary, Queen of Scots"], answer: "Francis Walsingham" },
  { q: "Who served as Lord Lieutenant to maintain order in the counties?", options: ["Local nobles", "Parliamentarians", "Privy Counsellors", "Justices of Peace"], answer: "Local nobles" },
  { q: "Which group supported Puritan reforms within the church?", options: ["Puritans", "Catholics", "Anglicans", "Lutherans"], answer: "Puritans" },
  { q: "Justices of the Peace were responsible for:", options: ["Local law and order", "Passing national laws", "Foreign policy", "Church discipline"], answer: "Local law and order" },
  { q: "Elizabeth’s main foreign threat in the 1560s came from:", options: ["France", "Scotland", "Spain", "Pope"], answer: "France" },
  { q: "Which country backed Northern Earls in their revolt?", options: ["Spain", "France", "Scotland", "Portugal"], answer: "Scotland" },
  { q: "Elizabeth’s legitimacy was also questioned because she was:", options: ["Female", "Foreign-born", "Protestant", "Unmarried"], answer: "Female" },
  { q: "Elizabeth’s government relied mainly on:", options: ["Patronage and loyalty", "Written constitutions", "Local councils", "Public elections"], answer: "Patronage and loyalty" },
  { q: "Who was a key figure promoting Protestantism in Scotland?", options: ["John Knox", "Puritans", "Francis Walsingham", "William Cecil"], answer: "John Knox" },
  { q: "Why was Mary, Queen of Scots, a threat to Elizabeth?", options: ["She had a claim and was Catholic", "She was French", "She was Protestant", "She was unmarried"], answer: "She had a claim and was Catholic" },
  { q: "Which plot of 1569 involved Northern Earls?", options: ["Northern Earls’ Revolt", "Ridolfi Plot", "Throckmorton Plot", "Babington Plot"], answer: "Northern Earls’ Revolt" },
  { q: "The Ridolfi Plot of 1571 aimed to:", options: ["Place Mary on the throne", "Invade Ireland", "Assassinate Cecil", "Overturn Religious Settlement"], answer: "Place Mary on the throne" },
  { q: "The Throckmorton Plot (1583) involved support from:", options: ["Spain", "France", "Pope", "Scotland"], answer: "Spain" },
  { q: "The Babington Plot (1586) aimed to:", options: ["Assassinate Elizabeth", "Redress taxes", "Support Puritans", "Overturn succession"], answer: "Assassinate Elizabeth" },
  { q: "Mary, Queen of Scots, was executed in:", options: ["1587", "1586", "1588", "1585"], answer: "1587" },
  { q: "Who led the intelligence operation against Mary’s conspiracies?", options: ["Walsingham", "Cecil", "Dudley", "Knox"], answer: "Walsingham" },
  { q: "Which country secretly funded plots against Elizabeth?", options: ["Spain", "France", "Scotland", "Papal States"], answer: "Spain" },
  { q: "The Northern Earls aimed to restore which religion?", options: ["Catholicism", "Puritanism", "Lutheranism", "Anglicanism"], answer: "Catholicism" },
  { q: "Ridolfi intended to install which monarch?", options: ["Mary, Queen of Scots", "Francis Drake", "Philip II", "Robert Cecil"], answer: "Mary, Queen of Scots" },
  { q: "Which plot led directly to Mary’s execution?", options: ["Babington Plot", "Throckmorton Plot", "Northern Earls’ Revolt", "Ridolfi Plot"], answer: "Babington Plot" },
  { q: "Elizabeth delayed executing Mary because:", options: ["She feared revolt", "Public support", "Spanish war", "Spanish marriage"], answer: "She feared revolt" },
  { q: "Who uncovered Throckmorton's secret letters?", options: ["Walsingham", "Cecil", "Knox", "Dudley"], answer: "Walsingham" },
  { q: "Mary escaped to England in:", options: ["1568", "1567", "1570", "1569"], answer: "1568" },
  { q: "Northern Earls hoped for support from:", options: ["Scotland and Spain", "France and the Pope", "Scotland and France", "Pope and England"], answer: "Scotland and Spain" },
  { q: "Mary’s execution provoked outrage from:", options: ["Catholics and Spain", "Puritans", "French Protestants", "Scotland"], answer: "Catholics and Spain" },
  { q: "Which plot was foiled using intercepted letters?", options: ["Babington Plot", "Northern Earls’ Revolt", "Ridolfi Plot", "Throckmorton Plot"], answer: "Babington Plot" },
  { q: "Mary was imprisoned in England for about", options: ["19 years", "5 years", "10 years", "15 years"], answer: "19 years" },
  { q: "After Mary’s execution, Spain prepared the:", options: ["Spanish Armada", "Ridolfi invasion", "Northern Rebellion", "Babington invasion"], answer: "Spanish Armada" },
  { q: "Who attacked Spanish ships and treasure?", options: ["Francis Drake", "Walter Raleigh", "John Hawkins", "Sir Philip Sidney"], answer: "Francis Drake" },
  { q: "The 'Singeing of the King of Spain’s Beard' was when Elizabeth:", options: ["Sent Drake to attack Cadiz", "Built navy", "Declared war", "Transported troops"], answer: "Sent Drake to attack Cadiz" },
  { q: "The Spanish Armada attempted invasion in:", options: ["1588", "1586", "1587", "1590"], answer: "1588" },
  { q: "Where was the decisive battle with the Armada fought?", options: ["Gravelines", "Calais", "Dover", "Trafalgar"], answer: "Gravelines" },
  { q: "England’s victory over Spain made it a:", options: ["Global naval power", "Land empire", "Catholic state", "Merchant republic"], answer: "Global naval power" },
  { q: "Walter Raleigh attempted to colonise:", options: ["Virginia", "New France", "Ireland", "Caribbean"], answer: "Virginia" },
  { q: "Exploration expanded during Elizabeth’s reign due to:", options: ["Privateers and trade", "Religion", "Treaties", "Mercenaries"], answer: "Privateers and trade" },
  { q: "Which route did Raleigh's expedition take?", options: ["Atlantic coast", "Pacific coast", "Northern passage", "Southern sea"], answer: "Atlantic coast" },
  { q: "Which treaty allied Spain with France and the Pope?", options: ["Treaty of Joinville", "Treaty of Calais", "Treaty of Rouen", "Treaty of London"], answer: "Treaty of Joinville" },
  { q: "Drake’s circumnavigation boosted:", options: ["England’s maritime prestige", "Land borders", "Religious unity", "Parliament’s power"], answer: "England’s maritime prestige" },
  { q: "Fish, furs, and tobacco were sourced from:", options: ["Virginia", "Spain", "France", "Mexico"], answer: "Virginia" },
  { q: "The Armada was hindered by storms in the:", options: ["English Channel", "Bay of Biscay", "Mediterranean", "Irish Sea"], answer: "English Channel" },
  { q: "Who sponsored voyages to Virginia?", options: ["Walter Raleigh", "Francis Drake", "John Hawkins", "Philip Sidney"], answer: "Walter Raleigh" },
  { q: "Drake’s voyages helped found:", options: ["English colonies", "Trade with Asia", "Church ties", "War alliances"], answer: "English colonies" },
  { q: "England’s naval success led to:", options: ["Expansion overseas", "Withdrawal from Europe", "Marriage alliances", "Religious unity"], answer: "Expansion overseas" },
  { q: "Exploration increased demand for:", options: ["Tobacco and sugar", "Spices", "Silk", "Gold coins"], answer: "Tobacco and sugar" },
  { q: "Failure in Virginia was due to:", options: ["Harsh environment", "Spanish attacks", "Disease", "Native resistance"], answer: "Harsh environment" },
  { q: "Raleigh named the area Virginia after:", options: ["Virgin Queen", "His wife", "St. Virginia", "Queen of Spain"], answer: "Virgin Queen" },
  { q: "England’s naval reforms included:", options: ["Fast and well-armed ships", "More cavalry", "New army tactics", "Diplomatic treaties"], answer: "Fast and well-armed ships" },
  { q: "Which event introduced Elizabethan Poor Laws?", options: ["1563", "1559", "1570", "1588"], answer: "1563" },
  { q: "The 1572 Poor Law created:", options: ["National poor rate", "Workhouses", "Charters", "Houses of corrections"], answer: "National poor rate" },
  { q: "Which leisure activity became popular in Elizabethan towns?", options: ["Theatre", "Polo", "Football", "Cricket"], answer: "Theatre" },
  { q: "Education in Elizabethan England was mainly for:", options: ["Wealthy boys", "Girls from all classes", "All children", "Foreigners"], answer: "Wealthy boys" },
  { q: "Grammar schools taught primarily in:", options: ["Latin", "English", "French", "Greek"], answer: "Latin" },
  { q: "Inns of Court trained:", options: ["Lawyers", "Doctors", "Priests", "Merchants"], answer: "Lawyers" },
  { q: "Young men explored the world as:", options: ["Privateers", "Farmers", "Merchants", "Educators"], answer: "Privateers" },
  { q: "Plays in the Globe were viewed by:", options: ["Commoners and nobles", "Only nobles", "Only commoners", "Foreigners"], answer: "Commoners and nobles" },
  { q: "Which explorer failed in Virginia?", options: ["Walter Raleigh", "Francis Drake", "John Hawkins", "Philip Sidney"], answer: "Walter Raleigh" },
  { q: "Elizabethans viewed the poor as:", options: ["A threat and responsibility", "The future rulers", "Foreigners", "Effective workers"], answer: "A threat and responsibility" },
  { q: "Vagabonds were:", options: ["Homeless beggars", "Landowners", "Merchants", "Nobles"], answer: "Homeless beggars" },
  { q: "People were punished for vagrancy by:", options: ["Whipping and branding", "Imprisonment", "Exile", "Tax"], answer: "Whipping and branding" },
  { q: "Education expanded due to:", options: ["Renaissance ideas", "Spanish influence", "Papal reforms", "Puritan push"], answer: "Renaissance ideas" },
  { q: "Leisure for upper classes included:", options: ["Hunting and fencing", "Football", "Cricket", "Theatre"], answer: "Hunting and fencing" },
  { q: "Common leisure included:", options: ["Public plays", "Opera", "Cinema", "Football"], answer: "Public plays" },
  { q: "Merchant wealth grew from:", options: ["Exploration and trade", "Taxation", "Mining", "Manufacturing"], answer: "Exploration and trade" },
  { q: "Elizabethan merchants traded goods such as:", options: ["Tobacco", "Tea", "Cotton", "Spices"], answer: "Tobacco" },
  { q: "The Poor Laws placed responsibility on:", options: ["Parishes", "The Crown", "Guilds", "Church"], answer: "Parishes" },
  { q: "Grammar schools prepared students for:", options: ["University", "Apprenticeship", "Clerking", "Farming"], answer: "University" },
  { q: "Popular theatre stories were often about:", options: ["Heroes, history and morality", "Science", "Football", "Foreign trade"], answer: "Heroes, history and morality" },
  { q: "Explorers often benefited from:", options: ["Royal patronage", "Church funding", "Parliament grants", "Merchant guilds"], answer: "Royal patronage" },
  { q: "Elizabethan England’s economy relied increasingly on:", options: ["Overseas trade", "Mining", "Manufacturing", "Church lands"], answer: "Overseas trade" },
  { q: "Leisure helped promote:", options: ["Social unity", "Dissent", "Education", "Tax"], answer: "Social unity" },
  { q: "Public theatre was seen as a:", options: ["Moral danger and entertainment", "Educational tool", "Church event", "Court ritual"], answer: "Moral danger and entertainment" },
  { q: "Grammar school fees were usually paid by:", options: ["Patrons or parents", "The Crown", "Church", "Guilds"], answer: "Patrons or parents" },
  { q: "Poor relief funding came from:", options: ["Parish taxes", "Foreign trade", "Charity only", "Royal grants"], answer: "Parish taxes" }
  ],
  coldwar: [
    {
      q: "What was the main purpose of the Truman Doctrine announced in 1947?",
      options: [
        "To contain the spread of communism",
        "To promote free trade",
        "To rebuild Europe economically",
        "To establish NATO"
      ],
      answer: "To contain the spread of communism"
    },
    {
      q: "What was the significance of the Marshall Plan?",
      options: ["It provided economic aid to rebuild Western Europe", "It created a military alliance", "It ended the Cold War", "It formed the Warsaw Pact"],
      answer: "It provided economic aid to rebuild Western Europe"
    },
    {
      q: "Which event marked the start of the Cold War?",
      options: ["The Iron Curtain speech by Churchill", "The Cuban Missile Crisis", "The Berlin Airlift", "The Korean War"],
      answer: "The Iron Curtain speech by Churchill"
    },
    {
      q: "What was the Warsaw Pact?",
      options: ["A military alliance of Eastern Bloc countries", "An economic agreement", "A peace treaty", "A nuclear arms deal"],
      answer: "A military alliance of Eastern Bloc countries"
    },
    {
      q: "What was NATO’s purpose when it was formed in 1949?",
      options: ["To provide collective security against Soviet aggression", "To promote trade", "To spread communism", "To end World War II"],
      answer: "To provide collective security against Soviet aggression"
    },
    {
      q: "Why did the Berlin Blockade occur in 1948?",
      options: ["Soviets aimed to force Allies out of West Berlin", "To stop Western aid to East Germany", "To unify Germany", "To prepare for war"],
      answer: "Soviets aimed to force Allies out of West Berlin"
    },
    {
      q: "What was the outcome of the Berlin Airlift?",
      options: ["Western Allies supplied West Berlin by air for almost a year", "Soviets captured West Berlin", "The airlift failed", "Germany was divided into three zones"],
      answer: "Western Allies supplied West Berlin by air for almost a year"
    },
    {
      q: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
      options: ["Nikita Khrushchev", "Joseph Stalin", "Leonid Brezhnev", "Mikhail Gorbachev"],
      answer: "Nikita Khrushchev"
    },
  { q: "Which year was the Tehran Conference held?", options: ["1941", "1943", "1945", "1947"], answer: "1943" },
  { q: "Which leaders attended the Tehran Conference?", options: ["Roosevelt, Churchill, Stalin", "Truman, Churchill, Stalin", "Roosevelt, Attlee, Stalin", "Eisenhower, Churchill, Stalin"], answer: "Roosevelt, Churchill, Stalin" },
  { q: "Which conference took place in February 1945?", options: ["Yalta", "Tehran", "Potsdam", "Geneva"], answer: "Yalta" },
  { q: "At Yalta, which organisation was agreed to be set up after the war?", options: ["United Nations", "NATO", "Warsaw Pact", "League of Nations"], answer: "United Nations" },
  { q: "Which country was divided into four zones at Yalta?", options: ["Germany", "Poland", "Czechoslovakia", "Austria"], answer: "Germany" },
  { q: "In July 1945, which conference was attended by Truman, Attlee, and Stalin?", options: ["Potsdam", "Yalta", "Tehran", "Helsinki"], answer: "Potsdam" },
  { q: "What event increased tension at the Potsdam Conference?", options: ["US testing of the atomic bomb", "Formation of NATO", "Berlin Blockade", "Hungarian Uprising"], answer: "US testing of the atomic bomb" },
  { q: "What term did Churchill use in 1946 to describe the divide between East and West Europe?", options: ["Iron Curtain", "Berlin Wall", "Cold Barrier", "Steel Divide"], answer: "Iron Curtain" },
  { q: "The Truman Doctrine was announced in which year?", options: ["1945", "1947", "1949", "1950"], answer: "1947" },
  { q: "What was the main aim of the Truman Doctrine?", options: ["Containment of communism", "Expansion of communism", "Nuclear disarmament", "Rebuilding Japan"], answer: "Containment of communism" },
  { q: "Which US policy provided economic aid to Europe to prevent the spread of communism?", options: ["Marshall Plan", "Truman Doctrine", "Berlin Airlift", "Helsinki Accords"], answer: "Marshall Plan" },
  { q: "How much money did the Marshall Plan offer to European countries?", options: ["$13 billion", "$5 billion", "$20 billion", "$50 billion"], answer: "$13 billion" },
  { q: "What was Cominform's main role?", options: ["Coordinate communist parties", "Plan economic aid", "Develop nuclear weapons", "Organise military alliances"], answer: "Coordinate communist parties" },
  { q: "Which Soviet economic organisation was set up in 1949?", options: ["Comecon", "Warsaw Pact", "Cominform", "Molotov Plan"], answer: "Comecon" },
  { q: "Which crisis began in June 1948?", options: ["Berlin Blockade", "Hungarian Uprising", "Cuban Missile Crisis", "Prague Spring"], answer: "Berlin Blockade" },
  { q: "How did the Western Allies respond to the Berlin Blockade?", options: ["Berlin Airlift", "Building the Berlin Wall", "Naval blockade", "Military invasion"], answer: "Berlin Airlift" },
  { q: "When was NATO formed?", options: ["1947", "1949", "1951", "1953"], answer: "1949" },
  { q: "Which countries were the main signatories of NATO in 1949?", options: ["USA, Canada, Western Europe", "USA, USSR, China", "USA, Eastern Europe, Britain", "USA, Japan, Britain"], answer: "USA, Canada, Western Europe" },
  { q: "When did the USSR test its first atomic bomb?", options: ["1947", "1949", "1951", "1955"], answer: "1949" },
  { q: "Which communist country split from Soviet control in 1948?", options: ["Yugoslavia", "Poland", "Czechoslovakia", "Hungary"], answer: "Yugoslavia" },
  { q: "Which defensive alliance did the USSR create in 1955?", options: ["Warsaw Pact", "Comecon", "NATO", "Molotov Pact"], answer: "Warsaw Pact" },
  { q: "What did the USA and Britain merge their German zones into in 1947?", options: ["Bizonia", "Trizonia", "Berlin Sector", "Marshall Zone"], answer: "Bizonia" },
  { q: "Which city was at the centre of Cold War tensions during the blockade of 1948–49?", options: ["Berlin", "Warsaw", "Prague", "Vienna"], answer: "Berlin" },
  { q: "What was the main Soviet aim in the Berlin Blockade?", options: ["Force Western Allies out of Berlin", "Test nuclear weapons", "Create a new currency", "Expand NATO"], answer: "Force Western Allies out of Berlin" },
  { q: "Which new currency did the West introduce in their zones in 1948?", options: ["Deutsche Mark", "Reichsmark", "Euro", "Allied Mark"], answer: "Deutsche Mark" },
  { q: "The Marshall Plan was partly a response to which Soviet action?", options: ["Communist takeover of Czechoslovakia", "Berlin Blockade", "Hungarian Uprising", "Afghanistan invasion"], answer: "Communist takeover of Czechoslovakia" },
  { q: "Which Soviet leader attended all three wartime conferences?", options: ["Joseph Stalin", "Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev"], answer: "Joseph Stalin" },
  { q: "Who succeeded Roosevelt as US President in 1945?", options: ["Harry Truman", "Dwight Eisenhower", "John Kennedy", "Lyndon Johnson"], answer: "Harry Truman" },
  { q: "The Long Telegram came from which US diplomat?", options: ["George Kennan", "Dean Acheson", "John Foster Dulles", "Henry Stimson"], answer: "George Kennan" },
  { q: "The Soviet equivalent to the Long Telegram was known as what?", options: ["Novikov Telegram", "Molotov Plan", "Cominform", "Iron Report"], answer: "Novikov Telegram" },
  { q: "What was the USA's main aim in the policy of containment?", options: ["Stop spread of communism", "Expand democracy", "End nuclear weapons", "Promote free trade"], answer: "Stop spread of communism" },
  { q: "Comecon was mainly created to counter which policy?", options: ["Marshall Plan", "Truman Doctrine", "Berlin Airlift", "Containment"], answer: "Marshall Plan" },
  { q: "When did Stalin die?", options: ["1953", "1952", "1954", "1951"], answer: "1953" },
  { q: "Which country became communist in 1949, increasing US fears?", options: ["China", "Poland", "Hungary", "Romania"], answer: "China" },
  { q: "What did the USSR demand from Turkey in 1946, alarming the USA?", options: ["Control of the Dardanelles", "Naval bases in Istanbul", "Military alliance", "Economic aid"], answer: "Control of the Dardanelles" },
  { q: "Which Eastern European country saw a communist coup in February 1948?", options: ["Czechoslovakia", "Poland", "Hungary", "Bulgaria"], answer: "Czechoslovakia" },
  { q: "What was the primary aim of the United Nations at its founding?", options: ["Maintain peace and security", "Promote communism", "Expand trade", "Create a world government"], answer: "Maintain peace and security" },
  { q: "Which city hosted the founding conference of the United Nations in 1945?", options: ["San Francisco", "New York", "London", "Geneva"], answer: "San Francisco" },
  { q: "What did the USA demonstrate in August 1945 that alarmed the USSR?", options: ["Atomic bomb capability", "Missile defence system", "Jet bombers", "Space rockets"], answer: "Atomic bomb capability" },
  { q: "Which agreement divided Germany into occupation zones in 1945?", options: ["Potsdam Agreement", "Yalta Agreement", "Tehran Agreement", "Berlin Treaty"], answer: "Yalta Agreement" },
  { q: "Who became leader of the USSR in 1955?", options: ["Nikita Khrushchev", "Joseph Stalin", "Leonid Brezhnev", "Mikhail Gorbachev"], answer: "Nikita Khrushchev" },
  { q: "Which defensive alliance did the USSR form in 1955?", options: ["Warsaw Pact", "Comecon", "NATO", "Molotov Pact"], answer: "Warsaw Pact" },
  { q: "Which country did the Warsaw Pact aim to protect from Western aggression?", options: ["Eastern European members", "USA", "China", "Japan"], answer: "Eastern European members" },
  { q: "Which country experienced a major uprising against Soviet control in 1956?", options: ["Hungary", "Poland", "Czechoslovakia", "Romania"], answer: "Hungary" },
  { q: "Who was the Hungarian leader during the 1956 uprising?", options: ["Imre Nagy", "Janos Kadar", "Alexander Dubcek", "Matyas Rakosi"], answer: "Imre Nagy" },
  { q: "What did Imre Nagy announce that alarmed the USSR?", options: ["Withdrawal from Warsaw Pact", "Nuclear weapon tests", "Alliance with USA", "Ban on communism"], answer: "Withdrawal from Warsaw Pact" },
  { q: "How did the USSR respond to the Hungarian uprising?", options: ["Military invasion", "Economic sanctions", "Diplomatic talks", "Withdrawal"], answer: "Military invasion" },
  { q: "Approximately how many Hungarians were killed in 1956?", options: ["2,500", "500", "5,000", "10,000"], answer: "2,500" },
  { q: "Which city was divided by a wall in 1961?", options: ["Berlin", "Vienna", "Warsaw", "Budapest"], answer: "Berlin" },
  { q: "What was the main reason for building the Berlin Wall?", options: ["Stop East Germans fleeing to the West", "Prevent Western invasion", "Mark city boundaries", "Divide military zones"], answer: "Stop East Germans fleeing to the West" },
  { q: "In what year was the Berlin Wall built?", options: ["1961", "1958", "1963", "1965"], answer: "1961" },
  { q: "Which US President faced Khrushchev during the Berlin Crisis of 1961?", options: ["John Kennedy", "Dwight Eisenhower", "Lyndon Johnson", "Richard Nixon"], answer: "John Kennedy" },
  { q: "The 'Checkpoint Charlie' standoff happened in which year?", options: ["1961", "1962", "1963", "1964"], answer: "1961" },
  { q: "Which island nation was at the centre of a nuclear crisis in 1962?", options: ["Cuba", "Cyprus", "Japan", "Greenland"], answer: "Cuba" },
  { q: "Which Soviet leader placed missiles in Cuba?", options: ["Nikita Khrushchev", "Joseph Stalin", "Leonid Brezhnev", "Mikhail Gorbachev"], answer: "Nikita Khrushchev" },
  { q: "Which US leader demanded missile removal from Cuba?", options: ["John Kennedy", "Dwight Eisenhower", "Lyndon Johnson", "Harry Truman"], answer: "John Kennedy" },
  { q: "What was the USA's response to Soviet missiles in Cuba?", options: ["Naval blockade", "Air strikes", "Land invasion", "Economic sanctions"], answer: "Naval blockade" },
  { q: "How many days did the Cuban Missile Crisis last?", options: ["13", "10", "20", "7"], answer: "13" },
  { q: "Which agreement ended the Cuban Missile Crisis?", options: ["USSR removed missiles from Cuba; USA removed missiles from Turkey", "Full disarmament", "USSR joined NATO", "US withdrew from Berlin"], answer: "USSR removed missiles from Cuba; USA removed missiles from Turkey" },
  { q: "In which year was the hotline between Washington and Moscow set up?", options: ["1963", "1962", "1964", "1965"], answer: "1963" },
  { q: "What did the 1963 Test Ban Treaty prohibit?", options: ["Nuclear tests in atmosphere, underwater, space", "Nuclear energy production", "Nuclear submarines", "Missile defence systems"], answer: "Nuclear tests in atmosphere, underwater, space" },
  { q: "What did the USA agree to sell to the USSR in the 1960s?", options: ["Grain", "Oil", "Steel", "Weapons"], answer: "Grain" },
  { q: "Which Czechoslovak leader promoted 'Socialism with a human face'?", options: ["Alexander Dubcek", "Imre Nagy", "Janos Kadar", "Gustav Husak"], answer: "Alexander Dubcek" },
  { q: "What reforms did Dubcek introduce in 1968?", options: ["Greater freedom of speech", "Nuclear weapons", "Military alliance with USA", "Ban on communism"], answer: "Greater freedom of speech" },
  { q: "Which event ended Dubcek's reforms?", options: ["Warsaw Pact invasion", "US invasion", "Economic crisis", "Dubcek resignation"], answer: "Warsaw Pact invasion" },
  { q: "How many Warsaw Pact troops entered Czechoslovakia in 1968?", options: ["500,000", "200,000", "100,000", "50,000"], answer: "500,000" },
  { q: "What was the Brezhnev Doctrine?", options: ["Right to intervene in any socialist country", "Ban on nuclear weapons", "Policy of peaceful coexistence", "Economic reform"], answer: "Right to intervene in any socialist country" },
  { q: "In 1968, which superpowers signed the Nuclear Non-Proliferation Treaty?", options: ["USA, USSR, UK", "USA, USSR, China", "USA, UK, France", "USSR, China, UK"], answer: "USA, USSR, UK" },
  { q: "The space race intensified after which Soviet achievement in 1961?", options: ["First man in space", "First satellite", "Moon landing", "Space station"], answer: "First man in space" },
  { q: "Who was the first man in space?", options: ["Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "Buzz Aldrin"], answer: "Yuri Gagarin" },
  { q: "Which US programme aimed to land a man on the Moon?", options: ["Apollo", "Mercury", "Gemini", "Voyager"], answer: "Apollo" },
  { q: "What did the USA achieve in 1969?", options: ["First man on the Moon", "First man in space", "First space station", "First space shuttle"], answer: "First man on the Moon" },
  { q: "Which country built the Berlin Wall?", options: ["East Germany", "West Germany", "Poland", "USSR"], answer: "East Germany" },
  { q: "What was the main US concern about the Berlin Wall?", options: ["Symbol of communist oppression", "Loss of trade", "Military threat", "Environmental damage"], answer: "Symbol of communist oppression" },
  { q: "The Cuban Missile Crisis brought the world close to what?", options: ["Nuclear war", "Economic collapse", "End of UN", "Civil war"], answer: "Nuclear war" },
  { q: "The USSR justified its 1968 invasion of Czechoslovakia using which policy?", options: ["Brezhnev Doctrine", "Marshall Plan", "Truman Doctrine", "Containment"], answer: "Brezhnev Doctrine" },
  { q: "In which year was the Brezhnev Doctrine announced?", options: ["1968", "1965", "1963", "1970"], answer: "1968" },
  { q: "What did the USA remove from Turkey as part of the Cuban Missile Crisis resolution?", options: ["Jupiter missiles", "Nuclear submarines", "Aircraft carriers", "Radar stations"], answer: "Jupiter missiles" },
  { q: "What was the main aim of the Test Ban Treaty of 1963?", options: ["Limit nuclear weapons testing", "Destroy nuclear weapons", "Ban space exploration", "Reduce military spending"], answer: "Limit nuclear weapons testing" },
  { q: "What does 'détente' mean in the context of the Cold War?", options: ["Relaxation of tensions", "Increase in tensions", "Nuclear arms race", "Military confrontation"], answer: "Relaxation of tensions" },
  { q: "Which US President pursued détente in the early 1970s?", options: ["Richard Nixon", "John Kennedy", "Jimmy Carter", "Ronald Reagan"], answer: "Richard Nixon" },
  { q: "Which Soviet leader worked with Nixon to improve relations?", options: ["Leonid Brezhnev", "Nikita Khrushchev", "Mikhail Gorbachev", "Joseph Stalin"], answer: "Leonid Brezhnev" },
  { q: "Which arms limitation agreement was signed in 1972?", options: ["SALT I", "SALT II", "START", "INF Treaty"], answer: "SALT I" },
  { q: "What did SALT I limit?", options: ["ICBMs and ABMs", "All nuclear weapons", "Military spending", "Space exploration"], answer: "ICBMs and ABMs" },
  { q: "What does ABM stand for?", options: ["Anti-Ballistic Missile", "Atomic Bomb Missile", "Advanced Ballistic Missile", "Armoured Ballistic Missile"], answer: "Anti-Ballistic Missile" },
  { q: "What was the main aim of SALT I?", options: ["Reduce nuclear arms competition", "Destroy all nuclear weapons", "Increase defence spending", "Expand NATO"], answer: "Reduce nuclear arms competition" },
  { q: "When was the Helsinki Accords signed?", options: ["1975", "1973", "1977", "1979"], answer: "1975" },
  { q: "How many countries signed the Helsinki Accords?", options: ["35", "25", "40", "30"], answer: "35" },
  { q: "Which area of agreement in the Helsinki Accords focused on human rights?", options: ["Basket Three", "Basket One", "Basket Two", "Basket Four"], answer: "Basket Three" },
  { q: "Which country hosted the Helsinki Conference?", options: ["Finland", "Sweden", "Norway", "Denmark"], answer: "Finland" },
  { q: "What was agreed under Basket One of the Helsinki Accords?", options: ["Security in Europe", "Human rights", "Economic cooperation", "Disarmament"], answer: "Security in Europe" },
  { q: "What was agreed under Basket Two of the Helsinki Accords?", options: ["Economic cooperation", "Nuclear disarmament", "Freedom of speech", "Military alliances"], answer: "Economic cooperation" },
  { q: "Which space mission symbolised cooperation in 1975?", options: ["Apollo-Soyuz", "Apollo 11", "Soyuz 1", "Voyager"], answer: "Apollo-Soyuz" },
  { q: "What did the Apollo-Soyuz mission involve?", options: ["Docking of US and Soviet spacecraft", "Moon landing", "Space station building", "Mars probe"], answer: "Docking of US and Soviet spacecraft" },
  { q: "Which US President signed SALT II?", options: ["Jimmy Carter", "Richard Nixon", "Gerald Ford", "Ronald Reagan"], answer: "Jimmy Carter" },
  { q: "When was SALT II signed?", options: ["1979", "1977", "1975", "1973"], answer: "1979" },
  { q: "Why was SALT II never ratified by the US Senate?", options: ["Soviet invasion of Afghanistan", "Nuclear accident", "Oil crisis", "Cuban Missile Crisis"], answer: "Soviet invasion of Afghanistan" },
  { q: "In which year did the USSR invade Afghanistan?", options: ["1979", "1978", "1980", "1977"], answer: "1979" },
  { q: "Who was the US President during the Soviet invasion of Afghanistan?", options: ["Jimmy Carter", "Richard Nixon", "Gerald Ford", "Ronald Reagan"], answer: "Jimmy Carter" },
  { q: "What action did the USA take in protest against the Soviet invasion of Afghanistan?", options: ["Boycotted 1980 Moscow Olympics", "Cut all trade", "Broke diplomatic ties", "Withdrew from NATO"], answer: "Boycotted 1980 Moscow Olympics" },
  { q: "Which country did the USA support in the Afghan conflict?", options: ["Mujahedeen", "Soviet army", "Taliban", "Afghan communists"], answer: "Mujahedeen" },
  { q: "What did the Carter Doctrine state?", options: ["US would use force to protect Persian Gulf interests", "US would invade the USSR", "US would withdraw from Europe", "US would destroy all nuclear weapons"], answer: "US would use force to protect Persian Gulf interests" },
  { q: "Which agreement in 1973 aimed to reduce tensions in the Middle East?", options: ["Yom Kippur ceasefire", "Camp David Accords", "Oslo Accords", "Geneva Protocol"], answer: "Yom Kippur ceasefire" },
  { q: "What major economic issue in the 1970s strained US-Soviet relations?", options: ["Oil crisis", "Grain shortage", "Stock market crash", "Space race costs"], answer: "Oil crisis" },
  { q: "Which Soviet leader attended the Helsinki Accords?", options: ["Leonid Brezhnev", "Nikita Khrushchev", "Mikhail Gorbachev", "Joseph Stalin"], answer: "Leonid Brezhnev" },
  { q: "Which leader replaced Nixon in 1974?", options: ["Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George Bush"], answer: "Gerald Ford" },
  { q: "What was a key limitation of the SALT agreements?", options: ["Did not reduce number of warheads", "Banned all missiles", "Ended space race", "Created one superpower"], answer: "Did not reduce number of warheads" },
  { q: "What was the USSR’s motivation for détente?", options: ["Economic problems", "Military superiority", "Desire to invade Europe", "End of communism"], answer: "Economic problems" },
  { q: "What was the USA’s motivation for détente?", options: ["Vietnam costs and social issues", "Military superiority", "Desire to expand communism", "Nuclear monopoly"], answer: "Vietnam costs and social issues" },
  { q: "Which part of the Helsinki Accords caused later disputes?", options: ["Human rights commitments", "Economic trade", "Nuclear testing", "Space cooperation"], answer: "Human rights commitments" },
  { q: "Which year marked the Apollo-Soyuz docking?", options: ["1975", "1974", "1976", "1977"], answer: "1975" },
  { q: "What was one symbolic outcome of Apollo-Soyuz?", options: ["Handshake in space", "Moon base construction", "Mars mission", "International space station"], answer: "Handshake in space" },
  { q: "Which crisis ended the period of détente in the 1970s?", options: ["Soviet invasion of Afghanistan", "Berlin Crisis", "Cuban Missile Crisis", "Hungarian Uprising"], answer: "Soviet invasion of Afghanistan" },
  { q: "Which sporting event did the USA boycott in 1980?", options: ["Moscow Olympics", "Los Angeles Olympics", "Seoul Olympics", "Montreal Olympics"], answer: "Moscow Olympics" },
  { q: "What was the Soviet response to the US Olympic boycott?", options: ["Boycotted 1984 Los Angeles Olympics", "Broke trade agreements", "Cut oil exports", "Ended SALT talks"], answer: "Boycotted 1984 Los Angeles Olympics" },
  { q: "Which year was the Carter Doctrine announced?", options: ["1980", "1979", "1978", "1977"], answer: "1980" },
  { q: "Which country was the main battleground in the Soviet-US confrontation after 1979?", options: ["Afghanistan", "Poland", "Iran", "East Germany"], answer: "Afghanistan" },
  { q: "Which US President was elected in 1980?", options: ["Ronald Reagan", "Jimmy Carter", "George Bush", "Bill Clinton"], answer: "Ronald Reagan" },
  { q: "What was Reagan's approach to the USSR often called?", options: ["Second Cold War", "Détente", "Perestroika", "Peace Offensive"], answer: "Second Cold War" },
  { q: "What did Reagan's military programme include?", options: ["Strategic Defense Initiative", "SALT III", "Apollo Program", "Marshall Plan"], answer: "Strategic Defense Initiative" },
  { q: "What nickname was given to the Strategic Defense Initiative?", options: ["Star Wars", "Space Shield", "Missile Dome", "Laser Net"], answer: "Star Wars" },
  { q: "What was the aim of SDI?", options: ["Protect USA from nuclear missiles", "Destroy Soviet missiles on launch pads", "Spy on Soviet bases", "Control space exploration"], answer: "Protect USA from nuclear missiles" },
  { q: "What impact did SDI have on the arms race?", options: ["Increased Soviet economic strain", "Ended the Cold War immediately", "Reduced US spending", "Strengthened Soviet military"], answer: "Increased Soviet economic strain" },
  { q: "Who became Soviet leader in 1985?", options: ["Mikhail Gorbachev", "Leonid Brezhnev", "Yuri Andropov", "Konstantin Chernenko"], answer: "Mikhail Gorbachev" },
  { q: "Which reform meant 'restructuring'?", options: ["Perestroika", "Glasnost", "Detente", "Solidarity"], answer: "Perestroika" },
  { q: "Which reform meant 'openness'?", options: ["Glasnost", "Perestroika", "Detente", "Solidarity"], answer: "Glasnost" },
  { q: "What problem did Gorbachev aim to solve with his reforms?", options: ["Economic stagnation", "Nuclear superiority", "Overpopulation", "Climate change"], answer: "Economic stagnation" },
  { q: "Which year saw the Geneva Summit between Reagan and Gorbachev?", options: ["1985", "1984", "1986", "1987"], answer: "1985" },
  { q: "Which summit in 1986 broke down over SDI disagreements?", options: ["Reykjavik", "Geneva", "Washington", "Moscow"], answer: "Reykjavik" },
  { q: "Which treaty in 1987 eliminated intermediate-range nuclear missiles?", options: ["INF Treaty", "SALT II", "START", "Nuclear Test Ban"], answer: "INF Treaty" },
  { q: "Where was the INF Treaty signed?", options: ["Washington", "Moscow", "Geneva", "Reykjavik"], answer: "Washington" },
  { q: "What was agreed at the Moscow Summit of 1988?", options: ["Ratification of INF Treaty", "Withdrawal from Afghanistan", "SDI cancellation", "Dissolution of NATO"], answer: "Ratification of INF Treaty" },
  { q: "When did Soviet troops begin to withdraw from Afghanistan?", options: ["1988", "1987", "1989", "1990"], answer: "1988" },
  { q: "Which Eastern European country saw the Solidarity movement challenge communist rule?", options: ["Poland", "Hungary", "East Germany", "Czechoslovakia"], answer: "Poland" },
  { q: "Who led the Solidarity movement?", options: ["Lech Wałęsa", "Vaclav Havel", "Imre Nagy", "Alexander Dubček"], answer: "Lech Wałęsa" },
  { q: "What was the nickname for the wave of revolutions in Eastern Europe in 1989?", options: ["Autumn of Nations", "Spring of Freedom", "Winter Revolution", "Summer of Change"], answer: "Autumn of Nations" },
  { q: "Which symbol of the Cold War was opened in November 1989?", options: ["Berlin Wall", "Iron Curtain", "Checkpoint Charlie", "Brandenburg Gate"], answer: "Berlin Wall" },
  { q: "Who was the East German leader forced to resign in 1989?", options: ["Erich Honecker", "Walter Ulbricht", "Egon Krenz", "Helmut Kohl"], answer: "Erich Honecker" },
  { q: "Which country’s border opening triggered the fall of the Berlin Wall?", options: ["Hungary", "Poland", "Czechoslovakia", "Austria"], answer: "Hungary" },
  { q: "Which summit in 1989 declared the end of the Cold War?", options: ["Malta Summit", "Moscow Summit", "Reykjavik Summit", "Helsinki Summit"], answer: "Malta Summit" },
  { q: "Who was the US President at the Malta Summit?", options: ["George Bush", "Ronald Reagan", "Bill Clinton", "Jimmy Carter"], answer: "George Bush" },
  { q: "When did the USSR formally dissolve?", options: ["1991", "1990", "1989", "1992"], answer: "1991" },
  { q: "Who became the first President of the Russian Federation?", options: ["Boris Yeltsin", "Mikhail Gorbachev", "Vladimir Putin", "Leonid Brezhnev"], answer: "Boris Yeltsin" },
  { q: "What was the failed coup against Gorbachev in 1991 called?", options: ["August Coup", "October Coup", "Winter Coup", "Kremlin Coup"], answer: "August Coup" },
  { q: "Which republic was first to declare independence from the USSR?", options: ["Lithuania", "Ukraine", "Georgia", "Latvia"], answer: "Lithuania" },
  { q: "What role did the arms race play in the Soviet collapse?", options: ["Economic burden", "Increased growth", "Military dominance", "Improved living standards"], answer: "Economic burden" },
  { q: "Which policy allowed Soviet citizens more freedom to criticise the government?", options: ["Glasnost", "Perestroika", "Solidarity", "Détente"], answer: "Glasnost" },
  { q: "Which year saw the Reykjavik Summit?", options: ["1986", "1985", "1987", "1988"], answer: "1986" },
  { q: "What did the INF Treaty remove?", options: ["Intermediate-range nuclear missiles", "All nuclear weapons", "Chemical weapons", "Ballistic missile submarines"], answer: "Intermediate-range nuclear missiles" },
  { q: "What was Gorbachev’s policy towards Eastern Europe?", options: ["Sinatra Doctrine", "Brezhnev Doctrine", "Iron Curtain", "Truman Doctrine"], answer: "Sinatra Doctrine" },
  { q: "What did the Sinatra Doctrine allow?", options: ["Eastern European countries to choose own governments", "Freedom of speech in USSR", "End of NATO", "Arms reduction"], answer: "Eastern European countries to choose own governments" },
  { q: "Which alliance dissolved in 1991 alongside the USSR?", options: ["Warsaw Pact", "NATO", "SEATO", "CENTO"], answer: "Warsaw Pact" },
  { q: "What was one consequence of the Soviet withdrawal from Afghanistan?", options: ["Loss of superpower status", "Victory over USA", "Expansion into the Middle East", "Nuclear war"], answer: "Loss of superpower status" },
  { q: "Which summit in 1990 focused on German reunification?", options: ["Paris Summit", "Moscow Summit", "Washington Summit", "Geneva Summit"], answer: "Paris Summit" },
  { q: "Who replaced Reagan as US President in 1989?", options: ["George Bush", "Bill Clinton", "Jimmy Carter", "Richard Nixon"], answer: "George Bush" }
  ],
  weimar: [
    {
      q: "What year was the Weimar Republic established?",
      options: ["1919", "1923", "1918", "1925"],
      answer: "1919"
    },
    {
      q: "What was the name of the treaty that ended WWI and affected Weimar Germany?",
      options: ["Treaty of Versailles", "Treaty of Tordesillas", "Treaty of Brest-Litovsk", "Treaty of Paris"],
      answer: "Treaty of Versailles"
    },
    {
      q: "What was the impact of the Treaty of Versailles on Germany?",
      options: ["Loss of territory and military restrictions", "Economic boom", "Political stability", "Increased army size"],
      answer: "Loss of territory and military restrictions"
    },
    {
      q: "Who was the first President of the Weimar Republic?",
      options: ["Friedrich Ebert", "Adolf Hitler", "Paul von Hindenburg", "Kaiser Wilhelm II"],
      answer: "Friedrich Ebert"
    },
    {
      q: "What was the 'Stab in the Back' myth?",
      options: ["Belief that Germany was betrayed by politicians", "Victory in WWI", "Economic recovery", "Treaty of Versailles support"],
      answer: "Belief that Germany was betrayed by politicians"
    },
    {
      q: "What was the purpose of the Dawes Plan?",
      options: ["Helped Germany pay reparations", "Punished Germany", "Started WWI", "Increased reparations"],
      answer: "Helped Germany pay reparations"
    },
    {
      q: "What was the impact of hyperinflation in 1923?",
      options: ["Money became worthless and savings were lost", "Economic stability", "Political peace", "Increased exports"],
      answer: "Money became worthless and savings were lost"
    },
    {
      q: "Who led the Munich Putsch in 1923?",
      options: ["Adolf Hitler", "Ernst Röhm", "Gustav Stresemann", "Friedrich Ebert"],
      answer: "Adolf Hitler"
    },
    {
      q: "What was the significance of the Dawes Plan?",
      options: ["Stabilised German economy and currency", "Started hyperinflation", "Ended Weimar Republic", "Led to war"],
      answer: "Stabilised German economy and currency"
    },
    {
      q: "What was the role of the Reichstag?",
      options: ["German parliament", "Army", "Judiciary", "President"],
      answer: "German parliament"
    }, 
  { q: "In which year did the Kaiser abdicate?", options: ["1917", "1918", "1919", "1920"], answer: "1918" },
  { q: "Who became the first President of the Weimar Republic?", options: ["Friedrich Ebert", "Paul von Hindenburg", "Gustav Stresemann", "Kurt von Schleicher"], answer: "Friedrich Ebert" },
  { q: "Where was the Weimar Constitution agreed upon?", options: ["Berlin", "Weimar", "Munich", "Hamburg"], answer: "Weimar" },
  { q: "Which term describes the belief that Germany was betrayed by its own politicians in 1918?", options: ["Stab in the Back", "Dawes Plan", "Locarno Pact", "Enabling Act"], answer: "Stab in the Back" },
  { q: "What was the maximum size of the German army under the Treaty of Versailles?", options: ["50,000", "100,000", "150,000", "200,000"], answer: "100,000" },
  { q: "Which territory was returned to France under the Treaty of Versailles?", options: ["Saarland", "Alsace-Lorraine", "Sudetenland", "East Prussia"], answer: "Alsace-Lorraine" },
  { q: "Which region was demilitarised under the Treaty of Versailles?", options: ["Bavaria", "Rhineland", "Pomerania", "Brandenburg"], answer: "Rhineland" },
  { q: "What year did Germany experience hyperinflation at its peak?", options: ["1920", "1921", "1923", "1925"], answer: "1923" },
  { q: "What triggered the French occupation of the Ruhr in 1923?", options: ["Missed reparations payment", "Election of new Chancellor", "Signing of the Dawes Plan", "Introduction of the Rentenmark"], answer: "Missed reparations payment" },
  { q: "Who introduced the Rentenmark to stabilise Germany's currency?", options: ["Gustav Stresemann", "Friedrich Ebert", "Adolf Hitler", "Hjalmar Schacht"], answer: "Gustav Stresemann" },
  { q: "Which plan in 1924 helped reorganise Germany’s reparations and loans?", options: ["Young Plan", "Four Year Plan", "Dawes Plan", "Marshall Plan"], answer: "Dawes Plan" },
  { q: "The Locarno Pact of 1925 improved relations between Germany and which country?", options: ["Britain", "France", "Italy", "Russia"], answer: "France" },
  { q: "In 1926, Germany joined which international organisation?", options: ["League of Nations", "United Nations", "NATO", "EEC"], answer: "League of Nations" },
  { q: "The Young Plan of 1929 aimed to do what?", options: ["Increase reparations", "Reduce reparations", "End reparations", "Freeze reparations"], answer: "Reduce reparations" },
  { q: "Which political group attempted the Kapp Putsch in 1920?", options: ["Right-wing Freikorps", "Communist Party", "NSDAP", "Social Democrats"], answer: "Right-wing Freikorps" },
  { q: "The Spartacist uprising in 1919 was led by which political group?", options: ["Communists", "Nazis", "Social Democrats", "Nationalists"], answer: "Communists" },
  { q: "Who were the leaders of the Spartacist uprising?", options: ["Rosa Luxemburg and Karl Liebknecht", "Adolf Hitler and Ernst Röhm", "Gustav Stresemann and Paul von Hindenburg", "Erich Ludendorff and Franz von Papen"], answer: "Rosa Luxemburg and Karl Liebknecht" },
  { q: "What was the name of the paramilitary units made up of ex-soldiers used to crush uprisings?", options: ["Freikorps", "SA", "SS", "Gestapo"], answer: "Freikorps" },
  { q: "What type of voting system did the Weimar Constitution introduce?", options: ["First-past-the-post", "Proportional representation", "Electoral college", "Block voting"], answer: "Proportional representation" },
  { q: "Which party was associated with Catholic voters in the Weimar period?", options: ["Zentrum Party", "SPD", "NSDAP", "KPD"], answer: "Zentrum Party" },
  { q: "In which year was the German Workers’ Party founded?", options: ["1917", "1918", "1919", "1920"], answer: "1919" },
  { q: "When did the German Workers’ Party become the NSDAP?", options: ["1919", "1920", "1921", "1922"], answer: "1920" },
  { q: "Who was in charge of Nazi propaganda in the early 1920s?", options: ["Joseph Goebbels", "Adolf Hitler", "Hermann Göring", "Greg Strasser"], answer: "Adolf Hitler" },
  { q: "The Munich Putsch took place in which year?", options: ["1921", "1922", "1923", "1924"], answer: "1923" },
  { q: "Which prominent general supported Hitler in the Munich Putsch?", options: ["Erich Ludendorff", "Paul von Hindenburg", "Heinz Guderian", "Werner von Blomberg"], answer: "Erich Ludendorff" },
  { q: "After the Munich Putsch, Hitler was sentenced to how many years in prison?", options: ["1", "3", "5", "10"], answer: "5" },
  { q: "How long did Hitler actually serve in prison after the Munich Putsch?", options: ["8 months", "1 year", "2 years", "3 years"], answer: "8 months" },
  { q: "What was the name of Hitler’s autobiography and political manifesto?", options: ["Mein Kampf", "Mein Reich", "Volk und Staat", "National Socialism"], answer: "Mein Kampf" },
  { q: "Who was appointed as Nazi Party treasurer in 1925?", options: ["Franz Schwarz", "Heinrich Himmler", "Hermann Göring", "Rudolf Hess"], answer: "Franz Schwarz" },
  { q: "Which event in 1929 deepened Germany’s economic crisis?", options: ["Wall Street Crash", "Locarno Pact", "Young Plan", "League of Nations entry"], answer: "Wall Street Crash" },
  { q: "In the 1930 election, how many seats did the Nazis win?", options: ["77", "107", "143", "196"], answer: "107" },
  { q: "Which paramilitary force was led by Ernst Röhm?", options: ["SA", "SS", "Gestapo", "Kripo"], answer: "SA" },
  { q: "Who was leader of the SS from 1929?", options: ["Heinrich Himmler", "Hermann Göring", "Reinhard Heydrich", "Walther Darré"], answer: "Heinrich Himmler" },
  { q: "Who became Chancellor before Hitler in 1932?", options: ["Franz von Papen", "Kurt von Schleicher", "Paul von Hindenburg", "Gustav Stresemann"], answer: "Franz von Papen" },
  { q: "Who was appointed Chancellor in December 1932?", options: ["Kurt von Schleicher", "Franz von Papen", "Adolf Hitler", "Joseph Goebbels"], answer: "Kurt von Schleicher" },
  { q: "When did Hitler become Chancellor?", options: ["January 1933", "February 1933", "March 1933", "April 1933"], answer: "January 1933" },
  { q: "Who was President when Hitler was appointed Chancellor?", options: ["Paul von Hindenburg", "Friedrich Ebert", "Erich Ludendorff", "Gustav Stresemann"], answer: "Paul von Hindenburg" },
  { q: "Which group did the Nazis blame for the Reichstag Fire?", options: ["Communists", "Social Democrats", "Conservatives", "Trade Unionists"], answer: "Communists" },
  { q: "Which law allowed Hitler to pass laws without Reichstag approval?", options: ["Enabling Act", "Nuremberg Laws", "Reich Concordat", "Locarno Pact"], answer: "Enabling Act" },
  { q: "The March 1933 election gave the Nazis what percentage of the vote?", options: ["43.9%", "50.1%", "37.4%", "29.6%"], answer: "43.9%" },
  { q: "Which event in 1934 consolidated Hitler’s power by removing SA leadership?", options: ["Night of the Long Knives", "Kristallnacht", "Reichstag Fire", "Beer Hall Putsch"], answer: "Night of the Long Knives" },
  { q: "Who was leader of the SA killed during the Night of the Long Knives?", options: ["Ernst Röhm", "Heinrich Himmler", "Hermann Göring", "Rudolf Hess"], answer: "Ernst Röhm" },
  { q: "What happened upon Hindenburg’s death in 1934?", options: ["Hitler became Führer", "Elections were held", "Weimar Constitution reinstated", "Communist government formed"], answer: "Hitler became Führer" },
  { q: "Which organisation acted as the Nazi secret police?", options: ["Gestapo", "SA", "SS", "Kripo"], answer: "Gestapo" },
  { q: "Who headed the Gestapo from 1936?", options: ["Heinrich Himmler", "Hermann Göring", "Reinhard Heydrich", "Walther Funk"], answer: "Reinhard Heydrich" },
  { q: "What was the main role of the People's Court?", options: ["To try political offences", "To manage trade unions", "To control media", "To register births"], answer: "To try political offences" },
  { q: "Which Nazi organisation controlled the police and concentration camps?", options: ["SS", "SA", "Gestapo", "RAD"], answer: "SS" },
  { q: "What was the primary purpose of the Reich Chamber of Culture?", options: ["Control cultural life", "Boost industry", "Manage foreign policy", "Oversee agriculture"], answer: "Control cultural life" },
  { q: "Which agreement in 1933 secured Catholic Church neutrality?", options: ["Reich Concordat", "Enabling Act", "Nuremberg Laws", "Four Year Plan"], answer: "Reich Concordat" },
  { q: "The Nuremberg Laws of 1935 targeted which group?", options: ["Jews", "Communists", "Trade Unionists", "Poles"], answer: "Jews" },
  { q: "What did the Nuremberg Laws ban?", options: ["Marriage between Jews and non-Jews", "Trade unions", "Political parties", "Public meetings"], answer: "Marriage between Jews and non-Jews" },
  { q: "Which event in 1938 saw attacks on Jewish property and synagogues?", options: ["Kristallnacht", "Night of the Long Knives", "Beer Hall Putsch", "May Day Riots"], answer: "Kristallnacht" },
  { q: "Who was Economics Minister during the Four Year Plan?", options: ["Hermann Göring", "Heinrich Himmler", "Walther Funk", "Rudolf Hess"], answer: "Hermann Göring" },
  { q: "What was the German Labour Front’s role?", options: ["Replace trade unions", "Control the army", "Oversee education", "Censor newspapers"], answer: "Replace trade unions" },
  { q: "Which programme offered leisure activities to workers?", options: ["Strength Through Joy", "Winter Relief Fund", "Beauty of Labour", "Volksgemeinschaft"], answer: "Strength Through Joy" },
  { q: "The Beauty of Labour programme focused on what?", options: ["Improving workplace conditions", "Propaganda films", "Youth camps", "Housing allocation"], answer: "Improving workplace conditions" },
  { q: "What did the 1935 reintroduction of conscription violate?", options: ["Treaty of Versailles", "Locarno Pact", "Reich Concordat", "Munich Agreement"], answer: "Treaty of Versailles" },
  { q: "What was the purpose of the RAD (Reich Labour Service)?", options: ["Provide jobs and military training", "Teach religion", "Organise elections", "Run propaganda"], answer: "Provide jobs and military training" },
  { q: "Who was Minister of Propaganda from 1933?", options: ["Joseph Goebbels", "Hermann Göring", "Rudolf Hess", "Heinrich Himmler"], answer: "Joseph Goebbels" },
  { q: "What was Hitler’s term for the 'people’s community'?", options: ["Volksgemeinschaft", "Lebensraum", "Anschluss", "Gleichschaltung"], answer: "Volksgemeinschaft" },
  { q: "Which youth organisation was compulsory for boys after 1936?", options: ["Hitler Youth", "Jungvolk", "League of German Boys", "Young Pioneers"], answer: "Hitler Youth" },
  { q: "What was the female equivalent of the Hitler Youth?", options: ["League of German Girls", "Young Maidens", "Women’s Corps", "German Sisterhood"], answer: "League of German Girls" },
  { q: "The Law for the Encouragement of Marriage offered what to couples?", options: ["Loans", "Free houses", "Tax breaks", "Land"], answer: "Loans" },
  { q: "What reward was given to women with many children?", options: ["Mother’s Cross", "Victory Medal", "Family Honour Award", "Fertility Star"], answer: "Mother’s Cross" },
  { q: "What was the Nazi policy of 'Lebensborn' intended for?", options: ["Increase 'Aryan' births", "Boost industrial output", "Train soldiers", "Resettle farmers"], answer: "Increase 'Aryan' births" },
  { q: "Which subject was given more time in Nazi schools?", options: ["Physical education", "Mathematics", "Geography", "Music"], answer: "Physical education" },
  { q: "What was the main Nazi aim in controlling education?", options: ["Indoctrinate youth", "Raise literacy", "Promote arts", "Increase trade skills"], answer: "Indoctrinate youth" },
  { q: "What was the 'Edelweiss Pirates' group known for?", options: ["Opposing Nazi youth groups", "Supporting Hitler", "Military training", "Helping the Gestapo"], answer: "Opposing Nazi youth groups" },
  { q: "Which religious group faced persecution for refusing military service?", options: ["Jehovah's Witnesses", "Catholics", "Lutherans", "Baptists"], answer: "Jehovah's Witnesses" },
  { q: "What was the Nazi stance on modern art?", options: ["Degenerate", "Essential", "Patriotic", "Neutral"], answer: "Degenerate" },
  { q: "What did the Winter Relief Campaign collect?", options: ["Donations for the poor", "Funds for the army", "Books", "Grain"], answer: "Donations for the poor" },
  { q: "Which profession saw women banned from practising by 1936?", options: ["Judges", "Teachers", "Doctors", "Factory workers"], answer: "Judges" },
  { q: "What was the Nazi ideal role for women?", options: ["Mother and homemaker", "Soldier", "Politician", "Business leader"], answer: "Mother and homemaker" },
  { q: "Which event marked the annexation of Austria in 1938?", options: ["Anschluss", "Lebensraum", "Kristallnacht", "Munich Agreement"], answer: "Anschluss" },
  { q: "What term did the Nazis use for territorial expansion?", options: ["Lebensraum", "Volksgemeinschaft", "Autarky", "Gleichschaltung"], answer: "Lebensraum" },
  { q: "Which Olympic Games did Germany host to promote Nazi ideals?", options: ["1936 Berlin", "1928 Amsterdam", "1940 Tokyo", "1932 Los Angeles"], answer: "1936 Berlin" },
  { q: "Who was the German female athlete who won gold in the 1936 Olympics?", options: ["Tilly Fleischer", "Leni Riefenstahl", "Christa Luding", "Magda Goebbels"], answer: "Tilly Fleischer" },
  { q: "Which film director created 'Triumph of the Will'?", options: ["Leni Riefenstahl", "Fritz Lang", "Josef von Sternberg", "Werner Herzog"], answer: "Leni Riefenstahl" },
  { q: "What was the Nazi policy of autarky aimed at?", options: ["Economic self-sufficiency", "Overseas trade", "Cultural purity", "Rapid rearmament"], answer: "Economic self-sufficiency" },
  { q: "What was the main aim of the Four Year Plan?", options: ["Prepare Germany for war", "Boost exports", "Improve housing", "Promote tourism"], answer: "Prepare Germany for war" }

  ]
};